___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [19]:
# np.random.randint(low=10, high=50, size=5)
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [20]:
# np.arange(10, 51, 2)
np.array([i for i in range(10, 51) if i % 2 == 0])

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

#### Use NumPy to generate a random number between 0 and 1

In [24]:
np.random.rand()

0.4580508014907264

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [26]:
np.random.normal(0, 1, 25)

array([-1.65020756, -1.84529531, -0.24371867, -0.21550683,  0.14174096,
       -1.00952145,  1.60866438,  0.24409308, -0.75925949,  1.06654871,
        0.43588425,  0.33711706,  1.20086775, -1.45465047,  1.41914366,
        0.09830374, -1.69556397,  0.16270336,  0.4280495 ,  0.10841228,
        0.58489892,  0.33700491, -0.90558174,  1.01955044, -0.51556772])

#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [27]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [28]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
# thay cac gia tri max cua mat bang NaN,nguoc lai thay bang gia tri nhan 2
new_mat = np.where(mat == mat.max(), np.NaN, mat*2)
new_mat

array([[ 2.,  4.,  6.,  8., 10.],
       [12., 14., 16., 18., 20.],
       [22., 24., 26., 28., 30.],
       [32., 34., 36., 38., 40.],
       [42., 44., 46., 48., nan]])

In [33]:
# tim index cua (cac) phan tu max
mat = np.array([[1,2,3],[3,2,1]])
tup = np.where(mat == mat.max())
rows = tup[0]
cols = tup[1]
z = zip(rows,cols)
cnt = 0
for r, c in z:
    cnt += 1
    print('phan tu thu', cnt, 'o hang ' , r, 'va cot', c)
mylist1 = [9,8,7,6]
mylist2 = [1,2,3,4]
myzip = zip(mylist1,mylist2)
for i, x in enumerate(myzip):
    print(i, x)

phan tu thu 1 o hang  0 va cot 2
phan tu thu 2 o hang  1 va cot 0
0 9
1 8
2 7
3 6


In [22]:
help(enumerate)

Help on class enumerate in module builtins:

class enumerate(object)
 |  enumerate(iterable, start=0)
 |  
 |  Return an enumerate object.
 |  
 |    iterable
 |      an object supporting iteration
 |  
 |  The enumerate object yields pairs containing a count (from start, which
 |  defaults to zero) and a value yielded by the iterable argument.
 |  
 |  enumerate is useful for obtaining an indexed list:
 |      (0, seq[0]), (1, seq[1]), (2, seq[2]), ...
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.



In [29]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y], /)
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x an

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [1]:
# abc = [16, 21, 26]
m = np.arange(12, 27)
filter = m not in [16, 21, 26]

NameError: name 'np' is not defined

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

325

#### Get the standard deviation of the values in mat

7.2111025509279782

#### Get the sum of all the columns in mat

array([55, 60, 65, 70, 75])

# Great Job!